import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import com.github.jengelman.gradle.plugins.shadow.relocation.SimpleRelocator

plugins {
	id "me.champeau.jmh" version "0.7.3"
    id "com.gradleup.shadow" version "9.0.0"
    id 'java-library'
    id 'idea'
    id 'eclipse'
}

compileJava.options.encoding = "UTF-8"

repositories {
    mavenCentral()
    maven {
    	name = 'Maven Central Snapshots' 
        url = 'https://central.sonatype.com/repository/maven-snapshots/' 
    }
}

configurations {
	jomlFields
    jomlRecords
}

task shadowJomlFields(type: ShadowJar) {
    group = 'shadow'
    configurations = [project.configurations.jomlFields]
    archiveClassifier = 'fields'
    relocate(new SimpleRelocator('org.joml', 'fields.org.joml', null, null))
}

task shadowJomlRecords(type: ShadowJar) {
    group = 'shadow'
    configurations = [project.configurations.jomlRecords]
    archiveClassifier = 'records'
    relocate(new SimpleRelocator('org.joml', 'records.org.joml', null, null))
}

dependencies {
	implementation "com.google.code.gson:gson:2.14.0"
	implementation "org.joml:joml:${JOML_VERSION}"
	implementation "com.github.oshi:oshi-core:6.6.1"
	implementation "org.lidiuma:lidiuma-math:${LIDIUMA_MATH_VERSION}";
	
	jomlFields "org.joml:joml2-fields:${JOML2_VERSION}"
    implementation files(shadowJomlFields.archiveFile)
	jmh files(shadowJomlFields.archiveFile)
	
	jomlRecords "org.joml:joml2-records:${JOML2_VERSION}"
    implementation files(shadowJomlRecords.archiveFile)
	jmh files(shadowJomlRecords.archiveFile)
}

jmh {
	includes = [
//		'benchmark.*'
//		'benchmark.joml.*'
//		'benchmark.joml2_fields.*'
//		'benchmark.joml2_records.*'
//		'benchmark.lidiuma_math.*'
	]
	humanOutputFile = null
    resultFormat = 'json'
    
    warmupIterations = 2
    iterations = 5
    timeOnIteration = '2s'
    warmup = '3s'
    fork = 1
    operationsPerInvocation = 5
    threads = 1
}

tasks.named('jmh') {
    finalizedBy('generateMarkdownResults')
}

tasks.withType(JavaCompile).configureEach { task ->
    task.dependsOn shadowJomlFields, shadowJomlRecords
}

tasks.matching { it.name.startsWith("jmh") }.configureEach { task ->
    task.dependsOn shadowJomlFields, shadowJomlRecords
}

task setup {
    group = 'internal'
    description = 'Sets the Project full up and generates the dependencies as needed'
    
    dependsOn shadowJomlFields, shadowJomlRecords
}

task generateMarkdownResults(type: JavaExec) {
	group = 'internal'
	description = 'Processes the Json Results into a markdown file'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'jomlbench.BenchmarkFormatter'
    args = ['build/results/jmh/results.json', 'results/temp', 'results/output/Benchmark - Latest.md']
}